services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: development
    ports:
      - "80:80"
      - "5173:5173"
    volumes:
      - .:/var/www/html
      - ./docker/log:/var/log/apache2
    #      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    links:
      - db:db
    environment:
      PHP_IDE_CONFIG: "serverName=localhost" # for debugging console commands in PHPStorm using Xdebug
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.laravel-cron.schedule: "@every 1m"
      ofelia.job-exec.laravel-cron.command: "php artisan schedule:run"

  ofelia:
    image: mcuadros/ofelia:0.3.20
    depends_on:
      - php
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  db:
    image: mariadb:11.4.9
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: dev_pulse

  adminer:
    image: adminer:5.4.1
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_PLUGINS: dark-switcher tables-filter

volumes:
  mariadb:
